export const STATUS_CODE = {
  OK: 200,
  CREATED: 201,
  ACCEPTED: 202,
  NO_CONTENT: 204,

  BAD_REQUEST: 400,
  UNAUTHORIZED: 401,
  FORBIDDEN: 403,
  NOT_FOUND: 404,
  METHOD_NOT_ALLOWED: 405,
  CONFLICT: 409,
  UNSUPPORTED_MEDIA_TYPE: 415,
  UNPROCESSABLE_ENTITY: 422,
  TOO_MANY_REQUESTS: 429,

  INTERNAL_SERVER_ERROR: 500,
  BAD_GATEWAY: 502,
  SERVICE_UNAVAILABLE: 503,
  GATEWAY_TIMEOUT: 504,
} as const;

export type httpStatusCode =
  | typeof STATUS_CODE.OK
  | typeof STATUS_CODE.CREATED
  | typeof STATUS_CODE.BAD_REQUEST
  | typeof STATUS_CODE.UNAUTHORIZED
  | typeof STATUS_CODE.FORBIDDEN
  | typeof STATUS_CODE.NOT_FOUND
  | typeof STATUS_CODE.CONFLICT
  | typeof STATUS_CODE.TOO_MANY_REQUESTS
  | typeof STATUS_CODE.INTERNAL_SERVER_ERROR;
